#setwd("D:/R/Week3/ProgAssignment3-data")
outcome<-read.csv("outcome-of-care-measures.csv",colClass="character")
head(outcome[,11])
outcome[,11]<-as.numeric(outcome[,11])
hist(outcome[,11],xlab="30-day Death Rate",ylab="Frequency",main="Heart Attack 30-day Death Rate")