par(mfrow=c(3,1))
hist(outcome[,11],xlab="30-day Death Rate",ylab="Frequency",main="Heart Attack 30-day Death Rate")
abline(v=median(na.omit(outcome[,11])))
outcome[,17]<-as.numeric(outcome[,17])
hist(outcome[,17],xlab="30-day Death Rate",ylab="Frequency",main="Heart Failure")
abline(v=median(na.omit(outcome[,17])))
outcome[,23]<-as.numeric(outcome[,23])
hist(outcome[,23],xlab="30-day Death Rate",ylab="Frequency",main="Pneumonia")
abline(v=median(na.omit(outcome[,23])))